#!/usr/bin/php
<?php
// Helper constants
define( 'DS', DIRECTORY_SEPARATOR );
define( 'PS', PATH_SEPARATOR );

define( 'ROOT_PATH', dirname( __FILE__ ) . DS );
define( 'LIBRARY_PATH', ROOT_PATH . 'lib' . DS );
define( 'TMP_PATH', DS . 'tmp' . DS );

// Set autoloading
require LIBRARY_PATH . 'Gezere' . DS . 'Autoloader.php';
$autoloader = new Gezere_Autoloader();
$autoloader->addPath( LIBRARY_PATH );
$autoloader->register();

$webdia = new Webdia_App( $_SERVER[ 'argv' ] );
$webdia->run();
