#!/usr/bin/php
<?php
define('DS', DIRECTORY_SEPARATOR);
define('PS', PATH_SEPARATOR);
define('ROOT_PATH', dirname(__FILE__) . DS);
define('LIBRARY_PATH', ROOT_PATH . 'lib' . DS);

// Set autoloading
require LIBRARY_PATH . 'Gezere' . DS . 'Autoloader.php';
$autoloader = new Gezere_Autoloader();
$autoloader->addPath( LIBRARY_PATH );
$autoloader->register();

// Load composer autoload.
require __DIR__ . DS . 'vendor' . DS . 'autoload.php';

$webdia = new Webdia_App($_SERVER['argv']);
$webdia->run();
